# Generated by Django 2.1.dev20180424160604 on 2018-09-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Federal',
            fields=[
                ('greater_than', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_bkt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('init_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_rate', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('federal_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('greater_than', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_bkt', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('init_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_rate', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('state_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('marital_status', models.CharField(choices=[('single', 'single'), ('married', 'married')], max_length=7)),
                ('zip_code', models.CharField(default='10016', max_length=6)),
            ],
        ),
    ]
